# Generated by Django 4.0.2 on 2022-02-09 14:47
from django.db import migrations

def seed(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Playlist = apps.get_model('waifufy', 'Playlist')
    Artist = apps.get_model('waifufy', 'Artist')
    Song = apps.get_model('waifufy', 'Song')

# user info
    admin = User(first_name='admin', last_name='mod', email='admin@email.com', username='admin', password='iamtheboss123', avatar='avatars/khaly2.png', is_staff=True, is_active=True)
    some_nerd = User(first_name='some', last_name='nerd', email='somenerd101@email.com', username='somenerd', password='geekyguy123', avatar='avatars/meeee.png', is_staff=False, is_active=True)
    a_nerd = User(first_name='a', last_name='nerd', email='aenerd101@email.com', username='anerd', password='sortageeky123', avatar='avatars/uwu.png', is_staff=False, is_active=True)
    not_a_nerd = User(first_name='nota', last_name='nerd', email='notanerd101@email.com', username='notanerd', password='notgeeky123', avatar='avatars/stacey2.png', is_staff=False, is_active=True)
    admin.save()
    some_nerd.save()
    a_nerd.save()
    not_a_nerd.save()
    
# playlist info
    anime_chill = Playlist(user=some_nerd, name='chill anime', description='my favorite chill anime songs :3')
    anime_hype = Playlist(user=some_nerd, name='hype anime', description='my favorite hype anime songs :3')
    lofi = Playlist(user=a_nerd, name='lofi', description='study music')
    rnb = Playlist(user=not_a_nerd, name='r&b', description='vibessss')
    sad_stuff = Playlist(user=not_a_nerd, name='sad stuff', description='i want to cry')
    random = Playlist(user=admin, name='random', description='i dont even know how to organize')
    anime_chill.save()
    anime_hype.save()
    lofi.save()
    rnb.save()
    sad_stuff.save()
    random.save()

# artist info
    xaster = Artist(name='xaster ft. maez', bio='annika, who goes by xaster loves to make music that reflect on the realities of mental health. she a gamer too lol', artist_image='artists/xasterthink.png')
    bruno = Artist(name='bruno mars', bio='you know who he is dont be dumb', artist_image='artists/bruno.jpg')
    doja = Artist(name='doja cat', bio='she sang the moo song and that blasted her career up', artist_image='artists/doja.jpg')
    giveon = Artist(name='given', bio='he got a deep voice and deep songs', artist_image='artists/giveon.jpg')
    james = Artist(name='james arthur', bio='dont know who he is but he has good sad music', artist_image='artists/james.png')
    kayou = Artist(name='kayou', bio='he does lofi', artist_image='artists/kayou.jpg')
    kina = Artist(name='kina', bio='he does lofi too', artist_image='artists/kina.jpg')
    luna = Artist(name='luna haruna', bio='he does lofi too', artist_image='artists/luna.jpg')
    niki = Artist(name='niki', bio='she is in 88rising', artist_image='artists/niki.jpg')
    olivia = Artist(name='olivia rodrigo', bio='some new artist that became popular', artist_image='artists/olivia.jpg')
    risa = Artist(name='risa', bio='japanese artist', artist_image='artists/risa.jpg')
    shawn = Artist(name='shawn mendes', bio='he just sings love songs', artist_image='artists/shawn.jpg')
    snow = Artist(name='snow', bio='lofi dude', artist_image='artists/snow.jpg')
    stereopony = Artist(name='stereopony', bio='a japanese band', artist_image='artists/stereopony.jpg')
    dane = Artist(name='dane amar', bio='he a bit lovely', artist_image='artist/dane.jpg')
    xaster.save()
    bruno.save()
    doja.save()
    giveon.save()
    james.save()
    kayou.save()
    kina.save()
    luna.save()
    niki.save()
    olivia.save()
    risa.save()
    shawn.save()
    snow.save()
    stereopony.save()
    dane.save()
    
# song info
    Song(artist=bruno, playlist=sad_stuff, name='when i was your man', song_image='songs/yourman.jpg', song_file='songs/wiwym.mp3').save()
    Song(artist=doja, playlist=rnb, name='you right', song_image='songs/youright.jpg', song_file='songs/yr.mp3').save()
    Song(artist=giveon, playlist=sad_stuff, name='like i want you', song_image='songs/likeiwantyou.png', song_file='songs/liwy.mp3').save()
    Song(artist=dane, playlist=rnb, name='green tea and honey', song_image='songs/greentea.jpg', song_file='songs/gtah.mp3').save()
    Song(artist=stereopony, playlist=anime_hype, name='hitohira no hanabi', song_image='songs/hito.png', song_file='songs/hitohira.mp3').save()
    Song(artist=james, playlist=sad_stuff, name='train wreck', song_image='songs/trainwreck.jpg', song_file='songs/trainwreck.mp3').save()
    Song(artist=kayou, playlist=lofi, name='i thought i had you', song_image='songs/hadyou.jpg', song_file='songs/hy.mp3').save()
    Song(artist=kina, playlist=lofi, name='get you the moon', song_image='songs/moon.jpg', song_file='songs/gytm.mp3').save()
    Song(artist=xaster, playlist=random, name='lost and found', song_image='songs/lost.jpg', song_file='songs/lost&found.mp3').save()
    Song(artist=luna, playlist=anime_chill, name='overfly', song_image='songs/overfly.png', song_file='songs/overfly.mp3').save()
    Song(artist=kina, playlist=lofi, name='get you the moon', song_image='songs/moon.jpg', song_file='songs/gytm.mp3').save()
    Song(artist=risa, playlist=anime_hype, name='yakusoku no kizuna', song_image='songs/yakusoku.jpg', song_file='songs/yakusoku.mp3').save()
    Song(artist=olivia, playlist=sad_stuff, name='happier', song_image='songs/happier.png', song_file='songs/happier.mp3').save()
    Song(artist=niki, playlist=rnb, name='lowkey', song_image='songs/lowkey.jpg', song_file='songs/lowkey.mp3').save()
    Song(artist=shawn, playlist=random, name='it will be okay', song_image='songs/beok.jpg', song_file='songs/beok.mp3').save()
    Song(artist=snow, playlist=lofi, name='i never wanna lose you', song_image='songs/snowlofi.jpg', song_file='songs/never.mp3').save()
    Song.playlist.set()

def fallow(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Playlist = apps.get_model('waifufy', 'Playlist')
    Artist = apps.get_model('waifufy', 'Artist')
    Song = apps.get_model('waifufy', 'Song')
    User.objects.all().delete()
    Playlist.objects.all().delete()
    Artist.objects.all().delete()
    Song.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('waifufy', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]

